# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2020 <placeholder>


include $(RTE_SDK)/mk/rte.vars.mk

APP = n3k-flr-test-app

CFLAGS += $(WERROR_FLAGS)

SRCS-y := main.c

include $(RTE_SDK)/mk/rte.app.mk
