/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) HCL TECHNOLOGIES LTD
 * Submitted on behalf of a third-party: Intel Corporation, a
 * Delaware corporation, having its principal place of business
 * at 2200 Mission College Boulevard,
 * Santa Clara, California 95052, USA
 */

#include "n3k_mgmt_rte_flow_parse_print.h"
#include "n3k_mgmt_rte_flow_parse.h"

const char* n3k_mgmt_parser_item_type_names[] = {
	[RTE_FLOW_ITEM_TYPE_END] = "RTE_FLOW_ITEM_TYPE_END",
	[RTE_FLOW_ITEM_TYPE_VOID] = "RTE_FLOW_ITEM_TYPE_VOID",
	[RTE_FLOW_ITEM_TYPE_INVERT] = "RTE_FLOW_ITEM_TYPE_INVERT",
	[RTE_FLOW_ITEM_TYPE_ANY] = "RTE_FLOW_ITEM_TYPE_ANY",
	[RTE_FLOW_ITEM_TYPE_PF] = "RTE_FLOW_ITEM_TYPE_PF",
	[RTE_FLOW_ITEM_TYPE_VF] = "RTE_FLOW_ITEM_TYPE_VF",
	[RTE_FLOW_ITEM_TYPE_PHY_PORT] = "RTE_FLOW_ITEM_TYPE_PHY_PORT",
	[RTE_FLOW_ITEM_TYPE_PORT_ID] = "RTE_FLOW_ITEM_TYPE_PORT_ID",
	[RTE_FLOW_ITEM_TYPE_RAW] = "RTE_FLOW_ITEM_TYPE_RAW",
	[RTE_FLOW_ITEM_TYPE_ETH] = "RTE_FLOW_ITEM_TYPE_ETH",
	[RTE_FLOW_ITEM_TYPE_VLAN] = "RTE_FLOW_ITEM_TYPE_VLAN",
	[RTE_FLOW_ITEM_TYPE_IPV4] = "RTE_FLOW_ITEM_TYPE_IPV4",
	[RTE_FLOW_ITEM_TYPE_IPV6] = "RTE_FLOW_ITEM_TYPE_IPV6",
	[RTE_FLOW_ITEM_TYPE_ICMP] = "RTE_FLOW_ITEM_TYPE_ICMP",
	[RTE_FLOW_ITEM_TYPE_UDP] = "RTE_FLOW_ITEM_TYPE_UDP",
	[RTE_FLOW_ITEM_TYPE_TCP] = "RTE_FLOW_ITEM_TYPE_TCP",
	[RTE_FLOW_ITEM_TYPE_SCTP] = "RTE_FLOW_ITEM_TYPE_SCTP",
	[RTE_FLOW_ITEM_TYPE_VXLAN] = "RTE_FLOW_ITEM_TYPE_VXLAN",
	[RTE_FLOW_ITEM_TYPE_E_TAG] = "RTE_FLOW_ITEM_TYPE_E_TAG",
	[RTE_FLOW_ITEM_TYPE_NVGRE] = "RTE_FLOW_ITEM_TYPE_NVGRE",
	[RTE_FLOW_ITEM_TYPE_MPLS] = "RTE_FLOW_ITEM_TYPE_MPLS",
	[RTE_FLOW_ITEM_TYPE_GRE] = "RTE_FLOW_ITEM_TYPE_GRE",
	[RTE_FLOW_ITEM_TYPE_FUZZY] = "RTE_FLOW_ITEM_TYPE_FUZZY",
	[RTE_FLOW_ITEM_TYPE_GTP] = "RTE_FLOW_ITEM_TYPE_GTP",
	[RTE_FLOW_ITEM_TYPE_GTPC] = "RTE_FLOW_ITEM_TYPE_GTPC",
	[RTE_FLOW_ITEM_TYPE_GTPU] = "RTE_FLOW_ITEM_TYPE_GTPU",
	[RTE_FLOW_ITEM_TYPE_ESP] = "RTE_FLOW_ITEM_TYPE_ESP",
	[RTE_FLOW_ITEM_TYPE_GENEVE] = "RTE_FLOW_ITEM_TYPE_GENEVE",
	[RTE_FLOW_ITEM_TYPE_VXLAN_GPE] = "RTE_FLOW_ITEM_TYPE_VXLAN_GPE",
	[RTE_FLOW_ITEM_TYPE_ARP_ETH_IPV4] = "RTE_FLOW_ITEM_TYPE_ARP_ETH_IPV4",
	[RTE_FLOW_ITEM_TYPE_IPV6_EXT] = "RTE_FLOW_ITEM_TYPE_IPV6_EXT",
	[RTE_FLOW_ITEM_TYPE_ICMP6] = "RTE_FLOW_ITEM_TYPE_ICMP6",
	[RTE_FLOW_ITEM_TYPE_ICMP6_ND_NS] = "RTE_FLOW_ITEM_TYPE_ICMP6_ND_NS",
	[RTE_FLOW_ITEM_TYPE_ICMP6_ND_NA] = "RTE_FLOW_ITEM_TYPE_ICMP6_ND_NA",
	[RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT] = "RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT",
	[RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT_SLA_ETH] = "RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT_SLA_ETH",
	[RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT_TLA_ETH] = "RTE_FLOW_ITEM_TYPE_ICMP6_ND_OPT_TLA_ETH",
	[RTE_FLOW_ITEM_TYPE_MARK] = "RTE_FLOW_ITEM_TYPE_MARK",
	[RTE_FLOW_ITEM_TYPE_META] = "RTE_FLOW_ITEM_TYPE_META",
	[RTE_FLOW_ITEM_TYPE_GRE_KEY] = "RTE_FLOW_ITEM_TYPE_GRE_KEY",
	[RTE_FLOW_ITEM_TYPE_GTP_PSC] = "RTE_FLOW_ITEM_TYPE_GTP_PSC",
	[RTE_FLOW_ITEM_TYPE_PPPOES] = "RTE_FLOW_ITEM_TYPE_PPPOES",
	[RTE_FLOW_ITEM_TYPE_PPPOED] = "RTE_FLOW_ITEM_TYPE_PPPOED",
	[RTE_FLOW_ITEM_TYPE_PPPOE_PROTO_ID] = "RTE_FLOW_ITEM_TYPE_PPPOE_PROTO_ID",
	[RTE_FLOW_ITEM_TYPE_NSH] = "RTE_FLOW_ITEM_TYPE_NSH",
	[RTE_FLOW_ITEM_TYPE_IGMP] = "RTE_FLOW_ITEM_TYPE_IGMP",
	[RTE_FLOW_ITEM_TYPE_AH] = "RTE_FLOW_ITEM_TYPE_AH",
	[RTE_FLOW_ITEM_TYPE_HIGIG2] = "RTE_FLOW_ITEM_TYPE_HIGIG2",
	[RTE_FLOW_ITEM_TYPE_TAG] = "RTE_FLOW_ITEM_TYPE_TAG",
};

const char* n3k_mgmt_parser_pattern_state_names[] = {
	[PATTERN_STATE_INVALID] = "PATTERN_STATE_INVALID",
	[PATTERN_STATE_START] = "PATTERN_STATE_START",
	[PATTERN_STATE_PORT_ID] = "PATTERN_STATE_PORT_ID",

	[PATTERN_STATE_OUTER_ETH] = "PATTERN_STATE_OUTER_ETH",
	[PATTERN_STATE_OUTER_IPV4] = "PATTERN_STATE_OUTER_IPV4",
	[PATTERN_STATE_OUTER_UDP] = "PATTERN_STATE_OUTER_UDP",
	[PATTERN_STATE_MPLS] = "PATTERN_STATE_MPLS",

	[PATTERN_STATE_INNER_ETH] = "PATTERN_STATE_INNER_ETH",
	[PATTERN_STATE_INNER_VLAN] = "PATTERN_STATE_INNER_VLAN",
	[PATTERN_STATE_INNER_IPV4] = "PATTERN_STATE_INNER_IPV4",
	[PATTERN_STATE_INNER_UDP] = "PATTERN_STATE_INNER_UDP",
	[PATTERN_STATE_INNER_TCP] = "PATTERN_STATE_INNER_TCP",

	[PATTERN_STATE_END] = "PATTERN_STATE_END",
	[PATTERN_STATE_MAX] = "PATTERN_STATE_MAX",
};

const char* n3k_mgmt_parser_flow_type_names[] = {
	[FLOW_TYPE_UNKNOWN] = "FLOW_TYPE_UNKNOWN",
	[FLOW_TYPE_LOCAL] = "FLOW_TYPE_LOCAL",
	[FLOW_TYPE_EGRESS] = "FLOW_TYPE_EGRESS",
	[FLOW_TYPE_INGRESS] = "FLOW_TYPE_INGRESS",
};

const char* n3k_mgmt_parser_action_state_names[] = {
	[ACTION_STATE_INVALID] = "ACTION_STATE_INVALID",
	[ACTION_STATE_START] = "ACTION_STATE_START",

	[ACTION_STATE_ROUTING_SMAC] = "ACTION_STATE_ROUTING_SMAC",
	[ACTION_STATE_ROUTING_SMAC_DMAC] = "ACTION_STATE_ROUTING_SMAC_DMAC",
	[ACTION_STATE_ROUTING_SMAC_DMAC_TTL] = "ACTION_STATE_ROUTING_SMAC_DMAC_TTL",

	[ACTION_STATE_SET_IPV4_DST] = "ACTION_STATE_SET_IPV4_DST",
	[ACTION_STATE_SET_IPV4_SRC] = "ACTION_STATE_SET_IPV4_SRC",

	[ACTION_STATE_RAW_ENCAP] = "ACTION_STATE_RAW_ENCAP",
	[ACTION_STATE_RAW_DECAP] = "ACTION_STATE_RAW_DECAP",
	[ACTION_STATE_RAW_DEC_TTL] = "ACTION_STATE_RAW_DEC_TTL",

	[ACTION_STATE_PORT_ID] = "ACTION_STATE_PORT_ID",

	[ACTION_STATE_PUSH_VLAN] = "ACTION_STATE_PUSH_VLAN",
	[ACTION_STATE_SET_VLAN_VID] = "ACTION_STATE_SET_VLAN_VID",
	[ACTION_STATE_SET_VLAN_PCP] = "ACTION_STATE_SET_VLAN_PCP",
	[ACTION_STATE_POP_VLAN] = "ACTION_STATE_POP_VLAN",

	[ACTION_STATE_MIRROR] = "ACTION_STATE_MIRROR",

	[ACTION_STATE_DROP] = "ACTION_STATE_DROP",

	[ACTION_STATE_END] = "ACTION_STATE_END",
	[ACTION_STATE_MAX] = "ACTION_STATE_MAX",
};

const char* n3k_mgmt_parser_action_type_names[] = {
	[RTE_FLOW_ACTION_TYPE_END] = "RTE_FLOW_ACTION_TYPE_END",
	[RTE_FLOW_ACTION_TYPE_VOID] = "RTE_FLOW_ACTION_TYPE_VOID",
	[RTE_FLOW_ACTION_TYPE_PASSTHRU] = "RTE_FLOW_ACTION_TYPE_PASSTHRU",
	[RTE_FLOW_ACTION_TYPE_JUMP] = "RTE_FLOW_ACTION_TYPE_JUMP",
	[RTE_FLOW_ACTION_TYPE_MARK] = "RTE_FLOW_ACTION_TYPE_MARK",
	[RTE_FLOW_ACTION_TYPE_FLAG] = "RTE_FLOW_ACTION_TYPE_FLAG",
	[RTE_FLOW_ACTION_TYPE_QUEUE] = "RTE_FLOW_ACTION_TYPE_QUEUE",
	[RTE_FLOW_ACTION_TYPE_DROP] = "RTE_FLOW_ACTION_TYPE_DROP",
	[RTE_FLOW_ACTION_TYPE_COUNT] = "RTE_FLOW_ACTION_TYPE_COUNT",
	[RTE_FLOW_ACTION_TYPE_RSS] = "RTE_FLOW_ACTION_TYPE_RSS",
	[RTE_FLOW_ACTION_TYPE_PF] = "RTE_FLOW_ACTION_TYPE_PF",
	[RTE_FLOW_ACTION_TYPE_VF] = "RTE_FLOW_ACTION_TYPE_VF",
	[RTE_FLOW_ACTION_TYPE_PHY_PORT] = "RTE_FLOW_ACTION_TYPE_PHY_PORT",
	[RTE_FLOW_ACTION_TYPE_PORT_ID] = "RTE_FLOW_ACTION_TYPE_PORT_ID",
	[RTE_FLOW_ACTION_TYPE_METER] = "RTE_FLOW_ACTION_TYPE_METER",
	[RTE_FLOW_ACTION_TYPE_SECURITY] = "RTE_FLOW_ACTION_TYPE_SECURITY",
	[RTE_FLOW_ACTION_TYPE_OF_SET_MPLS_TTL] = "RTE_FLOW_ACTION_TYPE_OF_SET_MPLS_TTL",
	[RTE_FLOW_ACTION_TYPE_OF_DEC_MPLS_TTL] = "RTE_FLOW_ACTION_TYPE_OF_DEC_MPLS_TTL",
	[RTE_FLOW_ACTION_TYPE_OF_SET_NW_TTL] = "RTE_FLOW_ACTION_TYPE_OF_SET_NW_TTL",
	[RTE_FLOW_ACTION_TYPE_OF_DEC_NW_TTL] = "RTE_FLOW_ACTION_TYPE_OF_DEC_NW_TTL",
	[RTE_FLOW_ACTION_TYPE_OF_COPY_TTL_OUT] = "RTE_FLOW_ACTION_TYPE_OF_COPY_TTL_OUT",
	[RTE_FLOW_ACTION_TYPE_OF_COPY_TTL_IN] = "RTE_FLOW_ACTION_TYPE_OF_COPY_TTL_IN",
	[RTE_FLOW_ACTION_TYPE_OF_POP_VLAN] = "RTE_FLOW_ACTION_TYPE_OF_POP_VLAN",
	[RTE_FLOW_ACTION_TYPE_OF_PUSH_VLAN] = "RTE_FLOW_ACTION_TYPE_OF_PUSH_VLAN",
	[RTE_FLOW_ACTION_TYPE_OF_SET_VLAN_VID] = "RTE_FLOW_ACTION_TYPE_OF_SET_VLAN_VID",
	[RTE_FLOW_ACTION_TYPE_OF_SET_VLAN_PCP] = "RTE_FLOW_ACTION_TYPE_OF_SET_VLAN_PCP",
	[RTE_FLOW_ACTION_TYPE_OF_POP_MPLS] = "RTE_FLOW_ACTION_TYPE_OF_POP_MPLS",
	[RTE_FLOW_ACTION_TYPE_OF_PUSH_MPLS] = "RTE_FLOW_ACTION_TYPE_OF_PUSH_MPLS",
	[RTE_FLOW_ACTION_TYPE_VXLAN_ENCAP] = "RTE_FLOW_ACTION_TYPE_VXLAN_ENCAP",
	[RTE_FLOW_ACTION_TYPE_VXLAN_DECAP] = "RTE_FLOW_ACTION_TYPE_VXLAN_DECAP",
	[RTE_FLOW_ACTION_TYPE_NVGRE_ENCAP] = "RTE_FLOW_ACTION_TYPE_NVGRE_ENCAP",
	[RTE_FLOW_ACTION_TYPE_NVGRE_DECAP] = "RTE_FLOW_ACTION_TYPE_NVGRE_DECAP",
	[RTE_FLOW_ACTION_TYPE_RAW_ENCAP] = "RTE_FLOW_ACTION_TYPE_RAW_ENCAP",
	[RTE_FLOW_ACTION_TYPE_RAW_DECAP] = "RTE_FLOW_ACTION_TYPE_RAW_DECAP",
	[RTE_FLOW_ACTION_TYPE_SET_IPV4_SRC] = "RTE_FLOW_ACTION_TYPE_SET_IPV4_SRC",
	[RTE_FLOW_ACTION_TYPE_SET_IPV4_DST] = "RTE_FLOW_ACTION_TYPE_SET_IPV4_DST",
	[RTE_FLOW_ACTION_TYPE_SET_IPV6_SRC] = "RTE_FLOW_ACTION_TYPE_SET_IPV6_SRC",
	[RTE_FLOW_ACTION_TYPE_SET_IPV6_DST] = "RTE_FLOW_ACTION_TYPE_SET_IPV6_DST",
	[RTE_FLOW_ACTION_TYPE_SET_TP_SRC] = "RTE_FLOW_ACTION_TYPE_SET_TP_SRC",
	[RTE_FLOW_ACTION_TYPE_SET_TP_DST] = "RTE_FLOW_ACTION_TYPE_SET_TP_DST",
	[RTE_FLOW_ACTION_TYPE_MAC_SWAP] = "RTE_FLOW_ACTION_TYPE_MAC_SWAP",
	[RTE_FLOW_ACTION_TYPE_DEC_TTL] = "RTE_FLOW_ACTION_TYPE_DEC_TTL",
	[RTE_FLOW_ACTION_TYPE_SET_TTL] = "RTE_FLOW_ACTION_TYPE_SET_TTL",
	[RTE_FLOW_ACTION_TYPE_SET_MAC_SRC] = "RTE_FLOW_ACTION_TYPE_SET_MAC_SRC",
	[RTE_FLOW_ACTION_TYPE_SET_MAC_DST] = "RTE_FLOW_ACTION_TYPE_SET_MAC_DST",
	[RTE_FLOW_ACTION_TYPE_INC_TCP_SEQ] = "RTE_FLOW_ACTION_TYPE_INC_TCP_SEQ",
	[RTE_FLOW_ACTION_TYPE_DEC_TCP_SEQ] = "RTE_FLOW_ACTION_TYPE_DEC_TCP_SEQ",
	[RTE_FLOW_ACTION_TYPE_INC_TCP_ACK] = "RTE_FLOW_ACTION_TYPE_INC_TCP_ACK",
	[RTE_FLOW_ACTION_TYPE_DEC_TCP_ACK] = "RTE_FLOW_ACTION_TYPE_DEC_TCP_ACK",
	[RTE_FLOW_ACTION_TYPE_SET_TAG] = "RTE_FLOW_ACTION_TYPE_SET_TAG",
	[RTE_FLOW_ACTION_TYPE_SET_META] = "RTE_FLOW_ACTION_TYPE_SET_META",
	[RTE_FLOW_ACTION_TYPE_MIRROR] = "RTE_FLOW_ACTION_TYPE_MIRROR",
};
