/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) HCL TECHNOLOGIES LTD
 * Submitted on behalf of a third-party: Intel Corporation, a
 * Delaware corporation, having its principal place of business
 * at 2200 Mission College Boulevard,
 * Santa Clara, California 95052, USA
 */

#ifndef _PMD_NET_N3K_MGMT_TUNNEL_TBL_REGS_API_H_
#define _PMD_NET_N3K_MGMT_TUNNEL_TBL_REGS_API_H_

#include "n3k_mgmt_regs.h"

enum MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_CMD_OP_TYPE {
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_CMD_WRITE = 1,
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_CMD_READ = 2,
};

struct __attribute__((packed, aligned(4))) tunnel_tbl_data_regs {
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_0_t data_0;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_1_t data_1;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_2_t data_2;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_3_t data_3;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_4_t data_4;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_5_t data_5;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_6_t data_6;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_7_t data_7;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_8_t data_8;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_9_t data_9;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_10_t data_10;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_11_t data_11;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_12_t data_12;
  MKS_VPORTLKUP_TUNNEL_TABLE_TUNNEL_TBL_DATA_13_t data_13;
